-- MySQL Script generated by MySQL Workbench
-- Fri May  3 18:32:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `mydb`.`Multiplex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Multiplex` (
  `idMultiplex` INT NOT NULL,
  `nombre_multiplex` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMultiplex`),
  UNIQUE INDEX `idMultiplex_UNIQUE` (`idMultiplex` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sala` (
  `idSala` INT NOT NULL,
  `idMultiplex` INT NOT NULL,
  `Cantidadfilas` INT NOT NULL,
  `CantidadColumnas` INT NOT NULL,
  `nombre_sala` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSala`),
  UNIQUE INDEX `idSala_UNIQUE` (`idSala` ASC),
    FOREIGN KEY (`idMultiplex`)
    REFERENCES `Multiplex` (`idMultiplex`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Silla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Silla` (
  `idSillas` INT NOT NULL,
  `idSala` INT NOT NULL,
  `UbicacionColumna` INT NOT NULL,
  `UbicacionFila` INT NOT NULL,
  `Estado` INT NOT NULL,
  `tipo_silla` VARCHAR(45) NOT NULL,
  `precio_silla` VARCHAR(45) NULL,
  PRIMARY KEY (`idSillas`),
  UNIQUE INDEX `idSillas_UNIQUE` (`idSillas` ASC),
    FOREIGN KEY (`idSala`)
    REFERENCES `Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL,
  `NumDocumento` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comida` (
  `idComida` INT NOT NULL,
  `nombre_comida` VARCHAR(45) NOT NULL,
  `tipo_comida` VARCHAR(45) NOT NULL,
  `precio_comida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComida`),
  UNIQUE INDEX `idComida_UNIQUE` (`idComida` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Factura` (
  `idFactura` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idSillas` INT NOT NULL,
  `idComida` INT NOT NULL,
  `CantidadSillas` INT NOT NULL,
  `CantidadComida` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  UNIQUE INDEX `idReserva_UNIQUE` (`idFactura` ASC),
    FOREIGN KEY (`idCliente`)
    REFERENCES `Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idSillas`)
    REFERENCES `Silla` (`idSillas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idComida`)
    REFERENCES `Comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empleado` (
  `idEmpleado` INT NOT NULL,
  `idMultiplex` INT NOT NULL,
  `nombre_empleado` VARCHAR(45) NOT NULL,
  `numero_telefono` VARCHAR(45) NOT NULL,
  `fecha_Contrato` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  UNIQUE INDEX `idEmpleado_UNIQUE` (`idEmpleado` ASC),
    FOREIGN KEY (`idMultiplex`)
    REFERENCES `Multiplex` (`idMultiplex`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Puntos` (
  `idPuntos` INT NOT NULL,
  `idFactura` INT NOT NULL,
  `TotalPuntos` INT NOT NULL,
  PRIMARY KEY (`idPuntos`),
  UNIQUE INDEX `idPuntos_UNIQUE` (`idPuntos` ASC),
    FOREIGN KEY (`idFactura`)
    REFERENCES `Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clasificacion` (
  `idClasificacion` INT NOT NULL AUTO_INCREMENT,
  `Detalle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClasificacion`),
  UNIQUE INDEX `idClasificacion_UNIQUE` (`idClasificacion` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
