-- MySQL Script generated by MySQL Workbench
-- Fri May  3 18:32:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `mydb`.`Multiplex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Multiplex` (
  `idMultiplex` INT NOT NULL,
  `nombre_multiplex` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMultiplex`),
  UNIQUE INDEX `idMultiplex_UNIQUE` (`idMultiplex` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sala` (
  `idSala` INT NOT NULL,
  `Multiplex_idMultiplex` INT NOT NULL,
  `Cantidadfilas` INT NOT NULL,
  `CantidadColumnas` INT NOT NULL,
  `nombre_sala` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSala`, `Multiplex_idMultiplex`),
  UNIQUE INDEX `idSala_UNIQUE` (`idSala` ASC),
  INDEX `fk_Sala_Multiplex1_idx` (`Multiplex_idMultiplex` ASC),
  CONSTRAINT `fk_Sala_Multiplex1`
    FOREIGN KEY (`Multiplex_idMultiplex`)
    REFERENCES `mydb`.`Multiplex` (`idMultiplex`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Silla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Silla` (
  `idSillas` INT NOT NULL,
  `Sala_idSala` INT NOT NULL,
  `UbicacionColumna` INT NOT NULL,
  `UbicacionFila` INT NOT NULL,
  `Estado` TINYINT NOT NULL,
  `tipo_silla` VARCHAR(45) NOT NULL,
  `precio_silla` VARCHAR(45) NULL,
  PRIMARY KEY (`idSillas`, `Sala_idSala`),
  UNIQUE INDEX `idSillas_UNIQUE` (`idSillas` ASC),
  INDEX `fk_Silla_Sala1_idx` (`Sala_idSala` ASC),
  CONSTRAINT `fk_Silla_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `mydb`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL,
  `NumDocumento` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comida` (
  `idComida` INT NOT NULL,
  `nombre_comida` VARCHAR(45) NOT NULL,
  `tipo_comida` VARCHAR(45) NOT NULL,
  `precio_comida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComida`),
  UNIQUE INDEX `idComida_UNIQUE` (`idComida` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Factura` (
  `idFactura` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Silla_idSillas` INT NOT NULL,
  `Comida_idComida` INT NOT NULL,
  `CantidadSillas` INT NOT NULL,
  `CantidadComida` INT NOT NULL,
  PRIMARY KEY (`idFactura`, `Silla_idSillas`, `Comida_idComida`, `Cliente_idCliente`),
  UNIQUE INDEX `idReserva_UNIQUE` (`idFactura` ASC),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Reserva_Silla1_idx` (`Silla_idSillas` ASC),
  INDEX `fk_Reserva_Comida1_idx` (`Comida_idComida` ASC),
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Silla1`
    FOREIGN KEY (`Silla_idSillas`)
    REFERENCES `mydb`.`Silla` (`idSillas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Comida1`
    FOREIGN KEY (`Comida_idComida`)
    REFERENCES `mydb`.`Comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empleado` (
  `idEmpleado` INT NOT NULL,
  `Multiplex_idMultiplex` INT NOT NULL,
  `nombre_empleado` VARCHAR(45) NOT NULL,
  `numero_telefono` VARCHAR(45) NOT NULL,
  `fecha_Contrato` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Multiplex_idMultiplex`),
  UNIQUE INDEX `idEmpleado_UNIQUE` (`idEmpleado` ASC),
  INDEX `fk_Empleado_Multiplex1_idx` (`Multiplex_idMultiplex` ASC),
  CONSTRAINT `fk_Empleado_Multiplex1`
    FOREIGN KEY (`Multiplex_idMultiplex`)
    REFERENCES `mydb`.`Multiplex` (`idMultiplex`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Puntos` (
  `idPuntos` INT NOT NULL,
  `Factura_idFactura` INT NOT NULL,
  `TotalPuntos` INT NOT NULL,
  `NumDocumento` INT NOT NULL,
  PRIMARY KEY (`idPuntos`, `Factura_idFactura`),
  UNIQUE INDEX `idPuntos_UNIQUE` (`idPuntos` ASC),
  INDEX `fk_Puntos_Reserva1_idx` (`Factura_idFactura` ASC),
  INDEX `fk_Puntos_Cliente1_idx` (`NumDocumento` ASC),
  CONSTRAINT `fk_Puntos_Reserva1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `mydb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puntos_Cliente1`
    FOREIGN KEY (`NumDocumento`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clasificacion` (
  `idClasificacion` INT NOT NULL AUTO_INCREMENT,
  `Detalle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClasificacion`),
  UNIQUE INDEX `idClasificacion_UNIQUE` (`idClasificacion` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
